service: api-gateway-teste

plugins:
  - serverless-plugin-canary-deployments
  - serverless-provisioned-concurrency-autoscaling
  - serverless-prune-plugin
  - fix-permissions

provider:
  name: aws
  runtime: nodejs12.x
  stackName: api-gateway-teste
  timeout: 30

  deploymentPrefix: serverless
  deploymentBucket: dzin-serverless-deploy

package:
  excludeDevDependencies: false
  individually: true
  exclude: ['**/**']

functions:
  hello:
    handler: handler.hello
    package:
      include: ['handler.js']
    provisionedConcurrency: 1
    concurrencyAutoscaling: true
    deploymentSettings:
      type: AllAtOnce
      alias: Live
    events:
      - http:
          cors: true
          path: /hello
          method: get

  farewell:
    handler: handler.hello
    package:
      include: ['handler.js']
    events:
      - http:
          cors: true
          path: /farewell
          method: get

# == CodeDeploy options ==
# Canary10Percent5Minutes
# Canary10Percent10Minutes
# Canary10Percent15Minutes
# Canary10Percent30Minutes
# Linear10PercentEvery1Minute
# Linear10PercentEvery2Minutes
# Linear10PercentEvery3Minutes
# Linear10PercentEvery10Minutes
# AllAtOnce

custom:
  prune:
    automatic: true
    number: 3
